version: '3'

services:
  minio:
    image: docker.io/bitnami/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    networks:
      - minionetwork
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=your_username
      - MINIO_ROOT_PASSWORD=your_password
      - MINIO_DEFAULT_BUCKETS=count-data
      - MINIO_SERVER_URL=http://localhost:9000
      - MINIO_SCHEME=http

  coordinator:
    image: mapreduce_coordinator
    ports: 
    - "7999:7999"
    command: ["uvicorn", "coordinator:app", "--host", "0.0.0.0", "--port", "7999"]
    networks:
      - minionetwork
  
  worker-1:
    image: mapreduce_worker
    command: ["uvicorn", "worker:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - minionetwork

  worker-2:
    image: mapreduce_worker
    command: ["uvicorn", "worker:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - minionetwork

  worker-3:
    image: mapreduce_worker
    command: ["uvicorn", "worker:app", "--host", "0.0.0.0", "--port", "8000"]
    networks:
      - minionetwork
  

networks:
  minionetwork:
    driver: bridge

volumes:
  minio_data:
    driver: local